### ISSUE TITLE
Running this software on OS X? 

### ISSUE THREAD

**Issue by rolgordijn** [johnlauer/serial-port-json-server#74]
This is the output that I get when running the 1.86 version on the latest version of Mac os X. I tried to disable the OS X firewall, but no succes either.

`1970/01/01 01:00:00 main.go:89: Version:1.86
fatal error: unexpected signal during runtime execution
[signal 0xa code=0x2 addr=0x1086a02fc8b pc=0x4108520]

goroutine 1 [running]:
runtime.throw(0x45515e0, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc82004bb90 sp=0xc82004bb78
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82004bbe0 sp=0xc82004bb90
sync.(*Pool).Get(0x46fba20, 0x0, 0x0)
	/usr/local/go/src/sync/pool.go:101 +0x40 fp=0xc82004bc30 sp=0xc82004bbe0
fmt.newPrinter(0x44d8d00)
	/usr/local/go/src/fmt/print.go:133 +0x27 fp=0xc82004bc70 sp=0xc82004bc30
fmt.Sprintln(0xc82004bf28, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:270 +0x28 fp=0xc82004bcc0 sp=0xc82004bc70
log.Println(0xc82004bf28, 0x2, 0x2)
	/usr/local/go/src/log/log.go:295 +0x35 fp=0xc82004bd08 sp=0xc82004bcc0
main.main()
	/Users/alden/Projects/proj82_go/src/serial-port-json-server/main.go:96 +0x3fa fp=0xc82004bf50 sp=0xc82004bd08
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82004bfa0 sp=0xc82004bf50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
`

**Comment by chilipeppr** [comment]
Any chance you could check out the source and compile with go? This feels
like a build issue. Lots of people use 1.86 on their Mac but more on
Windows and Linux, but the go runtime is very updated and they probably
fixed some esoteric bugs over the last year or so.

**Comment by jasonhillier** [comment]
I'm getting the same on MacOS 10.13.6 for version 1.86

Also tried older version 1.80, got:
`failed MSpanList_Insert 0x46c1000 0xc6a7447b7e79 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x45c24eb)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/panic.go:491 +0xad fp=0x7ffeefbff350 sp=0x7ffeefbff320
runtime.MSpanList_Insert(0x45e0a88, 0x46c1000)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbff378 sp=0x7ffeefbff350
MHeap_FreeSpanLocked(0x45dd680, 0x46c1000, 0x100)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbff3b8 sp=0x7ffeefbff378
MHeap_Grow(0x45dd680, 0x8, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbff3f8 sp=0x7ffeefbff3b8
MHeap_AllocSpanLocked(0x45dd680, 0x1, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbff438 sp=0x7ffeefbff3f8
mheap_alloc(0x45dd680, 0x1, 0x12, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbff460 sp=0x7ffeefbff438
runtime.MHeap_Alloc(0x45dd680, 0x1, 0x10000000012, 0x402bd89)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbff498 sp=0x7ffeefbff460
MCentral_Grow(0x45e53f8, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbff500 sp=0x7ffeefbff498
runtime.MCentral_CacheSpan(0x45e53f8, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbff538 sp=0x7ffeefbff500
runtime.MCache_Refill(0x46bd000, 0x12, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbff560 sp=0x7ffeefbff538
runtime.mcacheRefill_m()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbff580 sp=0x7ffeefbff560
runtime.onM(0x44ac350)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbff588 sp=0x7ffeefbff580
runtime.mallocgc(0x120, 0x43d89e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbff638 sp=0x7ffeefbff588
runtime.newobject(0x43d89e0, 0x46bd000)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbff660 sp=0x7ffeefbff638
runtime.newG(0x404541a)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbff678 sp=0x7ffeefbff660
allocg(0x45ea2e0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbff688 sp=0x7ffeefbff678
runtime.malg(0x8000, 0x45ea580)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbff6b8 sp=0x7ffeefbff688
runtime.mpreinit(0x45eaba0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbff6d0 sp=0x7ffeefbff6b8
mcommoninit(0x45eaba0)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbff6f8 sp=0x7ffeefbff6d0
runtime.schedinit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbff720 sp=0x7ffeefbff6f8
runtime.rt0_go(0x7ffeefbff768, 0x1, 0x7ffeefbff768, 0x0, 0x7fff64478015, 0x7fff64478015, 0x0, 0x1, 0x7ffeefbff910, 0x0, ...)
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbff728 sp=0x7ffeefbff720`

**Comment by jasonhillier** [comment]
Nevermind, it works with 1.96 release here:
https://github.com/chilipeppr/serial-port-json-server/releases
